vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        user_videos:
            uri_prefix:         '%app.path.user_videos%'
            upload_destination: '%kernel.project_dir%/public%app.path.user_videos%'

            # inject_on_load: false
            # delete_on_update: true
            # delete_on_remove: true
